name: Release Package

on:
  push:
    branches:
      - main
    paths:
      - 'dnd-ruleset/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Prepare NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install packages
        run: yarn

      - name: Build packages
        run: yarn workspace dnd-ruleset rollup -c

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: js-files
          path: dnd-ruleset/dist/*