name: Release Package

on:
  push:
    branches:
      - main
    paths:
      - 'dnd-ruleset/**'

jobs:
  build:
    strategy:
      matrix:
        registry: [github]

    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Prepare NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          registry-url: ${{ matrix.registry == 'github' && 'https://npm.pkg.github.com' || '' }}
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ matrix.registry == 'github' && secrets.PKG_GITHUB_TOKEN || secrets.NPM_GITHUB_TOKEN }}

      - name: Setup .yarnrc.yml
        if: ${{ matrix.registry == 'github' }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PKG_GITHUB_TOKEN }}" > ~/.npmrc
          echo "@senorihl:registry=https://npm.pkg.github.com" > ~/.npmrc
          yarn config set npmScopes.senorihl.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.senorihl.npmAlwaysAuth true
          yarn config set npmScopes.senorihl.npmAuthToken ${{ secrets.PKG_GITHUB_TOKEN }}

      - name: Build packages
        run: |
          yarn
          yarn workspace dnd-ruleset rollup -c
          if git --no-pager log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            ${{ matrix.registry == 'github' && 'sed -ibak ''s/dnd-ruleset/@senorihl\/dnd-ruleset/g'' dnd-ruleset/package.json' || '' }}
            yarn workspace ${{ matrix.registry == 'github' && '@senorihl/dnd-ruleset' || 'dnd-ruleset' }} publish
          else
            yarn workspace dnd-ruleset version --prepatch --preid "${{ github.sha }}" --no-git-tag-version
            ${{ matrix.registry == 'github' && 'sed -ibak ''s/dnd-ruleset/@senorihl\/dnd-ruleset/g'' dnd-ruleset/package.json' || '' }}
            yarn workspace ${{ matrix.registry == 'github' && '@senorihl/dnd-ruleset' || 'dnd-ruleset' }} publish --tag dev
          fi
        env:
          NODE_AUTH_TOKEN: ${{ matrix.registry == 'github' && secrets.PKG_GITHUB_TOKEN || secrets.NPM_GITHUB_TOKEN }}
